#!/usr/bin/env python3
"""
NOTE: THIS IS NOT AN EVELYN FILE. THIS WAS GENERATED BY SALIL TO DO PREPROCESSING IN A SIMILAR FORMAT 
AS WHAT EVELYN DID.
Minimal Preprocessing for TabPFN Experiment

Replicates the exact data cleaning and train-test split logic from the RF pipeline
(census_loop.py + preprocess.py) WITHOUT applying transformations like:
- Winsorization
- Log transform
- Normalization
- MICE imputation
- One-hot encoding

This ensures fair comparison: same data splits, but TabPFN on raw features.
"""

import pandas as pd
import numpy as np
import logging
from typing import Tuple, Optional

logger = logging.getLogger(__name__)


def generate_time_variables(data: pd.DataFrame, sale_date_col: str = 'sale_date') -> pd.DataFrame:
    """
    Generate time variables from sale_date column.
    Mirrors preprocess.py:248-303 (gen_time_vars)
    """
    data = data.copy()

    # Convert sale_date to datetime
    sale_date = data[sale_date_col].astype(str).str.zfill(8)
    sale_date = pd.to_datetime(sale_date, format='%Y%m%d', errors='coerce')

    # Generate time features
    data['sale_year'] = sale_date.dt.year
    data['sale_month'] = sale_date.dt.month
    data['sale_day_of_month'] = sale_date.dt.day
    data['sale_day_of_year'] = sale_date.dt.dayofyear
    data['sale_day_of_week'] = sale_date.dt.dayofweek

    # Days since Jan 1, 2000
    reference_date = pd.to_datetime('20000101', format='%Y%m%d')
    data['sale_day'] = (sale_date - reference_date).dt.days

    return data


def apply_minimal_cleaning(data: pd.DataFrame, label: str = 'SALE_AMOUNT') -> pd.DataFrame:
    """
    Apply minimal data cleaning that affects which rows exist.
    Mirrors census_loop.py lines 62-66 and preprocess.py cleaning methods.

    Steps:
    1. Drop multi/split parcels
    2. Drop null fips
    3. Drop null labels (SALE_AMOUNT)
    4. Generate time variables
    5. Drop repeat sales (keep last sale per property per year-month)
    """
    data = data.copy()

    initial_rows = len(data)
    logger.info(f"Initial data: {initial_rows} rows")

    # 1. Drop multi/split parcels (census_loop.py:62)
    data = data[data['MULTI_OR_SPLIT_PARCEL_CODE'].isnull()]
    logger.info(f"After dropping multi/split parcels: {len(data)} rows ({initial_rows - len(data)} dropped)")

    # 2. Drop null fips (census_loop.py:63)
    data = data[~data['fips'].isnull()]
    logger.info(f"After dropping null fips: {len(data)} rows")

    # 3. Drop null labels (preprocess.py:305 - drop_null_labels)
    data = data[~data[label].isnull()]
    logger.info(f"After dropping null labels: {len(data)} rows")

    # 4. Generate time variables (needed for drop_repeat_sales)
    if 'sale_date' in data.columns:
        data = generate_time_variables(data, sale_date_col='sale_date')
        logger.info("Generated time variables")

    # 5. Drop repeat sales (preprocess.py:454 - drop_repeat_sales with timebound=True)
    # Keep last sale per (CLIP, sale_year, sale_month)
    before_dedup = len(data)
    data = data.drop_duplicates(subset=['CLIP', 'sale_year', 'sale_month'], keep='last')
    logger.info(f"After dropping repeat sales: {len(data)} rows ({before_dedup - len(data)} duplicates removed)")

    # Reset index
    data = data.reset_index(drop=True)

    logger.info(f"Final cleaned data: {len(data)} rows (removed {initial_rows - len(data)} total)")

    return data


def train_test_split_by_year(data: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Replicate exact train-test split logic from preprocess.py:591-633.

    Logic:
    - If last year has >10% of data: test = last year, train = previous years
    - Otherwise: test = last 2 years, train = previous years

    Returns:
        (train_data, test_data)
    """
    if 'sale_year' not in data.columns:
        raise ValueError("sale_year column not found. Run generate_time_variables first.")

    data = data.copy()
    max_year = data['sale_year'].max()

    # Check if last year has sufficient data (>10%)
    last_year_mask = data['sale_year'] == max_year
    last_year_size = last_year_mask.sum()
    last_year_pct = last_year_size / len(data)

    logger.info(f"Max year: {max_year}, samples: {last_year_size} ({last_year_pct:.2%} of data)")

    if last_year_pct > 0.1:
        # Test = last year only
        test_mask = data['sale_year'] == max_year
        train_mask = data['sale_year'] < max_year
        logger.info(f"Using last year ({max_year}) as test set")
    else:
        # Test = last 2 years
        test_mask = data['sale_year'] >= (max_year - 1)
        train_mask = data['sale_year'] < (max_year - 1)
        logger.info(f"Using last 2 years ({max_year-1}, {max_year}) as test set")

    train_data = data[train_mask].reset_index(drop=True)
    test_data = data[test_mask].reset_index(drop=True)

    logger.info(f"Train set: {len(train_data)} samples")
    logger.info(f"Test set: {len(test_data)} samples")

    return train_data, test_data


def process_county(county_data: pd.DataFrame,
                  fips_code: int,
                  min_samples: int = 100,
                  label: str = 'SALE_AMOUNT') -> Optional[Tuple[pd.DataFrame, pd.DataFrame]]:
    """
    Process a single county: apply minimal cleaning and train-test split.

    Args:
        county_data: Raw county data
        fips_code: FIPS code for logging
        min_samples: Minimum samples required (RF pipeline uses 100)
        label: Target variable name

    Returns:
        (train_data, test_data) or None if county should be skipped
    """
    logger.info(f"=" * 80)
    logger.info(f"Processing county {fips_code}")
    logger.info(f"=" * 80)

    # Skip counties with insufficient data (census_loop.py:100)
    if len(county_data) < min_samples:
        logger.warning(f"County {fips_code} has insufficient data ({len(county_data)} < {min_samples}), skipping")
        return None

    # Apply minimal cleaning
    try:
        cleaned_data = apply_minimal_cleaning(county_data, label=label)
    except Exception as e:
        logger.error(f"Error during cleaning for county {fips_code}: {e}")
        return None

    # Check if sufficient data remains after cleaning
    if len(cleaned_data) < min_samples:
        logger.warning(f"County {fips_code} has insufficient data after cleaning ({len(cleaned_data)} < {min_samples}), skipping")
        return None

    # Additional check: census_loop.py:109-110
    # Skip if CALCULATED_TOTAL_VALUE is missing for >10% of homes
    if 'CALCULATED_TOTAL_VALUE' in cleaned_data.columns:
        null_pct = cleaned_data['CALCULATED_TOTAL_VALUE'].isnull().sum() / len(cleaned_data)
        if null_pct > 0.10:
            logger.warning(f"County {fips_code}: CALCULATED_TOTAL_VALUE missing for {null_pct:.2%} > 10%, skipping")
            return None

    # Train-test split by year
    try:
        train_data, test_data = train_test_split_by_year(cleaned_data)
    except Exception as e:
        logger.error(f"Error during train-test split for county {fips_code}: {e}")
        return None

    # Ensure both splits have data
    if len(train_data) == 0 or len(test_data) == 0:
        logger.warning(f"County {fips_code}: Empty train or test set after split, skipping")
        return None

    logger.info(f"County {fips_code} processing complete")
    logger.info(f"  Train: {len(train_data)} samples, years {train_data['sale_year'].min()}-{train_data['sale_year'].max()}")
    logger.info(f"  Test: {len(test_data)} samples, years {test_data['sale_year'].min()}-{test_data['sale_year'].max()}")

    return train_data, test_data


def process_all_counties(data_path: str,
                        output_train_path: Optional[str] = None,
                        output_test_path: Optional[str] = None,
                        fips_list: Optional[list] = None,
                        nrows: Optional[int] = None) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Process all counties in dataset.

    Args:
        data_path: Path to full dataset
        output_train_path: Optional path to save combined train data
        output_test_path: Optional path to save combined test data
        fips_list: Optional list of FIPS codes to process (if None, process all)
        nrows: Optional number of rows to load (for testing)

    Returns:
        (all_train_data, all_test_data)
    """
    # Load data
    logger.info(f"Loading data from {data_path}")
    if nrows:
        logger.info(f"Loading only first {nrows} rows for testing")

    data = pd.read_csv(data_path, nrows=nrows)
    logger.info(f"Loaded data shape: {data.shape}")

    # Get list of counties to process
    if fips_list is None:
        fips_list = sorted(data['fips'].dropna().unique())

    logger.info(f"Processing {len(fips_list)} counties")

    all_train = []
    all_test = []
    successful_counties = 0
    skipped_counties = 0

    for fips_code in fips_list:
        county_data = data[data['fips'] == fips_code]

        result = process_county(county_data, int(fips_code))

        if result is not None:
            train_data, test_data = result

            # Add fips to data if not present
            if 'fips' not in train_data.columns:
                train_data['fips'] = fips_code
                test_data['fips'] = fips_code

            all_train.append(train_data)
            all_test.append(test_data)
            successful_counties += 1
        else:
            skipped_counties += 1

    logger.info(f"=" * 80)
    logger.info(f"PROCESSING COMPLETE")
    logger.info(f"=" * 80)
    logger.info(f"Successfully processed: {successful_counties} counties")
    logger.info(f"Skipped: {skipped_counties} counties")

    # Combine all data
    if all_train:
        train_combined = pd.concat(all_train, ignore_index=True)
        test_combined = pd.concat(all_test, ignore_index=True)

        logger.info(f"Combined train data: {len(train_combined)} samples from {train_combined['fips'].nunique()} counties")
        logger.info(f"Combined test data: {len(test_combined)} samples from {test_combined['fips'].nunique()} counties")

        # Save if paths provided
        if output_train_path:
            train_combined.to_csv(output_train_path, index=False)
            logger.info(f"Train data saved to {output_train_path}")

        if output_test_path:
            test_combined.to_csv(output_test_path, index=False)
            logger.info(f"Test data saved to {output_test_path}")

        return train_combined, test_combined
    else:
        logger.error("No counties processed successfully")
        return pd.DataFrame(), pd.DataFrame()


if __name__ == "__main__":
    import argparse

    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler('minimal_preprocessing.log', mode='w')
        ]
    )

    parser = argparse.ArgumentParser(description='Minimal preprocessing for TabPFN experiment')
    parser.add_argument('--data_path', type=str,
                       default='/nlp/scr/salilg/corelogic_census_2018_2023.csv',
                       help='Path to full dataset')
    parser.add_argument('--output_train', type=str, default='train_data.csv',
                       help='Output path for train data')
    parser.add_argument('--output_test', type=str, default='test_data.csv',
                       help='Output path for test data')
    parser.add_argument('--nrows', type=int, default=None,
                       help='Number of rows to load (for testing)')

    args = parser.parse_args()

    train_data, test_data = process_all_counties(
        data_path=args.data_path,
        output_train_path=args.output_train,
        output_test_path=args.output_test,
        nrows=args.nrows
    )

    if not train_data.empty:
        print(f"\nProcessing complete!")
        print(f"Train samples: {len(train_data)}")
        print(f"Test samples: {len(test_data)}")
        print(f"Counties: {train_data['fips'].nunique()}")
