#!/usr/bin/env python3
"""
NOTE: GENERATED BY SALIL TO VALIDATE TEST SET MATCHING BETWEEN RF AND TABPFN.
Validate Test Set Matching

Compares the test sets generated by minimal_preprocessing.py against the
RF pipeline results to ensure they match.

Matching criteria: (CLIP, SALE_YEAR) since RF results don't have sale_date.
Handles multiple matches (same property, same year, multiple sales).
"""

import pandas as pd
import numpy as np
import logging
from typing import Dict, Tuple
from collections import defaultdict

logger = logging.getLogger(__name__)


def load_rf_test_identifiers(rf_results_path: str) -> pd.DataFrame:
    """
    Load test set identifiers from RF results.
    Uses (CLIP, fips, SALE_YEAR) as unique identifiers.

    Returns:
        DataFrame with columns: CLIP, fips, SALE_YEAR
    """
    logger.info(f"Loading RF results from {rf_results_path}")
    rf_results = pd.read_csv(rf_results_path)

    logger.info(f"RF results shape: {rf_results.shape}")
    logger.info(f"RF results columns: {rf_results.columns.tolist()}")

    # Extract test identifiers
    test_ids = rf_results[['CLIP', 'fips', 'SALE_YEAR']].copy()

    # Drop duplicates (shouldn't be any, but just in case)
    initial_len = len(test_ids)
    test_ids = test_ids.drop_duplicates()
    if len(test_ids) < initial_len:
        logger.warning(f"Dropped {initial_len - len(test_ids)} duplicate (CLIP, SALE_YEAR) pairs from RF results")

    logger.info(f"RF test identifiers: {len(test_ids)} samples from {test_ids['fips'].nunique()} counties")

    return test_ids


def load_tabpfn_test_set(test_data_path: str) -> pd.DataFrame:
    """
    Load test set generated by minimal_preprocessing.py.

    Returns:
        DataFrame with test data
    """
    logger.info(f"Loading TabPFN test set from {test_data_path}")
    test_data = pd.read_csv(test_data_path)

    logger.info(f"TabPFN test set shape: {test_data.shape}")
    logger.info(f"TabPFN test set columns: {test_data.columns.tolist()}")

    # Extract identifiers
    if 'SALE_YEAR' not in test_data.columns and 'sale_year' in test_data.columns:
        test_data['SALE_YEAR'] = test_data['sale_year']

    required_cols = ['CLIP', 'fips', 'SALE_YEAR']
    missing_cols = [col for col in required_cols if col not in test_data.columns]
    if missing_cols:
        raise ValueError(f"Missing required columns in TabPFN test set: {missing_cols}")

    logger.info(f"TabPFN test identifiers: {len(test_data)} samples from {test_data['fips'].nunique()} counties")

    return test_data


def validate_county(rf_test_ids: pd.DataFrame,
                   tabpfn_test_data: pd.DataFrame,
                   fips_code: int) -> Dict:
    """
    Validate test set matching for a single county.

    Args:
        rf_test_ids: RF test identifiers for this county
        tabpfn_test_data: TabPFN test data for this county
        fips_code: FIPS code

    Returns:
        Dict with validation metrics
    """
    # Extract (CLIP, SALE_YEAR) tuples
    rf_tuples = set(zip(rf_test_ids['CLIP'], rf_test_ids['SALE_YEAR']))
    tabpfn_tuples = set(zip(tabpfn_test_data['CLIP'], tabpfn_test_data['SALE_YEAR']))

    # Calculate set differences
    in_rf_only = rf_tuples - tabpfn_tuples
    in_tabpfn_only = tabpfn_tuples - rf_tuples
    in_both = rf_tuples & tabpfn_tuples

    # Handle multiple matches (same CLIP, same SALE_YEAR, multiple sales)
    # Count occurrences in TabPFN test set
    tabpfn_clip_year_counts = defaultdict(int)
    for clip, year in tabpfn_tuples:
        tabpfn_clip_year_counts[(clip, year)] += 1

    multiple_matches = [(clip, year, count) for (clip, year), count in tabpfn_clip_year_counts.items() if count > 1]

    match_rate = len(in_both) / len(rf_tuples) * 100 if rf_tuples else 0

    results = {
        'fips': fips_code,
        'rf_test_size': len(rf_tuples),
        'tabpfn_test_size': len(tabpfn_tuples),
        'matches': len(in_both),
        'match_rate_pct': match_rate,
        'in_rf_only': len(in_rf_only),
        'in_tabpfn_only': len(in_tabpfn_only),
        'perfect_match': len(in_rf_only) == 0 and len(in_tabpfn_only) == 0,
        'multiple_matches': len(multiple_matches),
    }

    return results, in_rf_only, in_tabpfn_only, multiple_matches


def validate_all_counties(rf_results_path: str,
                         tabpfn_test_path: str,
                         output_summary_path: str = None,
                         verbose: bool = True) -> pd.DataFrame:
    """
    Validate test set matching across all counties.

    Args:
        rf_results_path: Path to RF pipeline results CSV
        tabpfn_test_path: Path to TabPFN test set CSV (from minimal_preprocessing.py)
        output_summary_path: Optional path to save validation summary
        verbose: Whether to print detailed per-county results

    Returns:
        DataFrame with per-county validation metrics
    """
    # Load data
    rf_test_ids = load_rf_test_identifiers(rf_results_path)
    tabpfn_test_data = load_tabpfn_test_set(tabpfn_test_path)

    # Get counties present in both
    rf_counties = set(rf_test_ids['fips'].unique())
    tabpfn_counties = set(tabpfn_test_data['fips'].unique())

    counties_in_both = rf_counties & tabpfn_counties
    counties_rf_only = rf_counties - tabpfn_counties
    counties_tabpfn_only = tabpfn_counties - rf_counties

    logger.info(f"=" * 80)
    logger.info(f"COUNTY COVERAGE")
    logger.info(f"=" * 80)
    logger.info(f"Counties in RF results: {len(rf_counties)}")
    logger.info(f"Counties in TabPFN test set: {len(tabpfn_counties)}")
    logger.info(f"Counties in both: {len(counties_in_both)}")
    logger.info(f"Counties in RF only: {len(counties_rf_only)}")
    logger.info(f"Counties in TabPFN only: {len(counties_tabpfn_only)}")

    if counties_rf_only:
        logger.warning(f"Counties in RF results but not in TabPFN test set: {sorted(counties_rf_only)[:10]}...")
    if counties_tabpfn_only:
        logger.warning(f"Counties in TabPFN test set but not in RF results: {sorted(counties_tabpfn_only)[:10]}...")

    # Validate each county
    logger.info(f"\n" + "=" * 80)
    logger.info(f"VALIDATING TEST SETS FOR {len(counties_in_both)} COUNTIES")
    logger.info(f"=" * 80)

    validation_results = []
    perfect_match_counties = []
    mismatch_counties = []

    for fips_code in sorted(counties_in_both):
        rf_county = rf_test_ids[rf_test_ids['fips'] == fips_code]
        tabpfn_county = tabpfn_test_data[tabpfn_test_data['fips'] == fips_code]

        results, in_rf_only, in_tabpfn_only, multiple_matches = validate_county(
            rf_county, tabpfn_county, int(fips_code)
        )

        validation_results.append(results)

        if results['perfect_match']:
            perfect_match_counties.append(fips_code)
        else:
            mismatch_counties.append(fips_code)

        if verbose and not results['perfect_match']:
            logger.info(f"\nCounty {fips_code}:")
            logger.info(f"  RF test size: {results['rf_test_size']}")
            logger.info(f"  TabPFN test size: {results['tabpfn_test_size']}")
            logger.info(f"  Matches: {results['matches']} ({results['match_rate_pct']:.2f}%)")
            logger.info(f"  In RF only: {results['in_rf_only']}")
            logger.info(f"  In TabPFN only: {results['in_tabpfn_only']}")

            if results['multiple_matches'] > 0:
                logger.warning(f"  Multiple matches found: {results['multiple_matches']} (CLIP, SALE_YEAR) pairs")
                logger.warning(f"    Examples: {multiple_matches[:3]}")

            if in_rf_only and len(in_rf_only) <= 5:
                logger.warning(f"  Samples in RF only: {list(in_rf_only)}")

            if in_tabpfn_only and len(in_tabpfn_only) <= 5:
                logger.warning(f"  Samples in TabPFN only: {list(in_tabpfn_only)}")

    # Create summary DataFrame
    summary_df = pd.DataFrame(validation_results)

    # Overall statistics
    logger.info(f"\n" + "=" * 80)
    logger.info(f"VALIDATION SUMMARY")
    logger.info(f"=" * 80)
    logger.info(f"Total counties validated: {len(summary_df)}")
    logger.info(f"Perfect matches: {len(perfect_match_counties)} ({len(perfect_match_counties)/len(summary_df)*100:.2f}%)")
    logger.info(f"Mismatches: {len(mismatch_counties)} ({len(mismatch_counties)/len(summary_df)*100:.2f}%)")
    logger.info(f"\nOverall statistics:")
    logger.info(f"  Total RF test samples: {summary_df['rf_test_size'].sum()}")
    logger.info(f"  Total TabPFN test samples: {summary_df['tabpfn_test_size'].sum()}")
    logger.info(f"  Total matches: {summary_df['matches'].sum()}")
    logger.info(f"  Overall match rate: {summary_df['matches'].sum() / summary_df['rf_test_size'].sum() * 100:.2f}%")
    logger.info(f"\nMismatch statistics:")
    logger.info(f"  Mean match rate: {summary_df['match_rate_pct'].mean():.2f}%")
    logger.info(f"  Median match rate: {summary_df['match_rate_pct'].median():.2f}%")
    logger.info(f"  Min match rate: {summary_df['match_rate_pct'].min():.2f}%")
    logger.info(f"  Counties with <100% match: {(summary_df['match_rate_pct'] < 100).sum()}")
    logger.info(f"  Counties with multiple matches: {(summary_df['multiple_matches'] > 0).sum()}")

    if len(mismatch_counties) > 0:
        logger.warning(f"\nCounties with mismatches:")
        worst_matches = summary_df.nsmallest(10, 'match_rate_pct')
        for _, row in worst_matches.iterrows():
            logger.warning(f"  FIPS {int(row['fips'])}: {row['match_rate_pct']:.2f}% match "
                         f"(RF: {row['rf_test_size']}, TabPFN: {row['tabpfn_test_size']}, "
                         f"RF only: {row['in_rf_only']}, TabPFN only: {row['in_tabpfn_only']})")

    # Save summary
    if output_summary_path:
        summary_df.to_csv(output_summary_path, index=False)
        logger.info(f"\nValidation summary saved to {output_summary_path}")

    return summary_df


def explain_mismatches(summary_df: pd.DataFrame):
    """
    Provide explanations for common mismatch patterns.
    """
    logger.info(f"\n" + "=" * 80)
    logger.info(f"MISMATCH EXPLANATIONS")
    logger.info(f"=" * 80)

    # Check for systematic differences
    total_rf = summary_df['rf_test_size'].sum()
    total_tabpfn = summary_df['tabpfn_test_size'].sum()
    diff_pct = (total_tabpfn - total_rf) / total_rf * 100

    logger.info(f"Overall test set size difference: {diff_pct:+.2f}%")

    if abs(diff_pct) < 1:
        logger.info("✓ Test set sizes are very close overall - likely minor edge case differences")
    elif diff_pct > 0:
        logger.info("⚠ TabPFN test set is LARGER - possible causes:")
        logger.info("  - Not dropping repeat sales correctly")
        logger.info("  - Different handling of null values")
        logger.info("  - Missing some data cleaning step")
    else:
        logger.info("⚠ TabPFN test set is SMALLER - possible causes:")
        logger.info("  - Over-aggressive data cleaning")
        logger.info("  - Different handling of edge cases in year-based split")

    # Check for multiple matches issue
    counties_with_multiples = (summary_df['multiple_matches'] > 0).sum()
    if counties_with_multiples > 0:
        logger.warning(f"\n⚠ {counties_with_multiples} counties have multiple matches")
        logger.warning("  This means same (CLIP, SALE_YEAR) appears multiple times in TabPFN test set")
        logger.warning("  Likely cause: drop_repeat_sales not applied correctly")
        logger.warning("  RF pipeline keeps only LAST sale per (CLIP, sale_year, sale_month)")

    # Check for systematic "in RF only" vs "in TabPFN only"
    total_rf_only = summary_df['in_rf_only'].sum()
    total_tabpfn_only = summary_df['in_tabpfn_only'].sum()

    logger.info(f"\nSamples only in RF: {total_rf_only}")
    logger.info(f"Samples only in TabPFN: {total_tabpfn_only}")

    if total_rf_only > total_tabpfn_only * 2:
        logger.warning("  TabPFN is missing many samples from RF test set")
        logger.warning("  Possible causes: data file mismatch, over-aggressive filtering")
    elif total_tabpfn_only > total_rf_only * 2:
        logger.warning("  TabPFN has many extra samples not in RF test set")
        logger.warning("  Possible causes: not applying all RF cleaning steps")


if __name__ == "__main__":
    import argparse

    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler('validate_test_sets.log', mode='w')
        ]
    )

    parser = argparse.ArgumentParser(description='Validate test set matching between RF and TabPFN')
    parser.add_argument('--rf_results', type=str,
                       default='/nlp/scr/salilg/census_loop_rf_bg_only_results.csv',
                       help='Path to RF pipeline results CSV')
    parser.add_argument('--tabpfn_test', type=str,
                       default='test_data.csv',
                       help='Path to TabPFN test set (from minimal_preprocessing.py)')
    parser.add_argument('--output_summary', type=str,
                       default='validation_summary.csv',
                       help='Output path for validation summary')
    parser.add_argument('--verbose', action='store_true',
                       help='Print detailed per-county results')

    args = parser.parse_args()

    summary_df = validate_all_counties(
        rf_results_path=args.rf_results,
        tabpfn_test_path=args.tabpfn_test,
        output_summary_path=args.output_summary,
        verbose=args.verbose
    )

    if summary_df is not None and not summary_df.empty:
        explain_mismatches(summary_df)

        perfect_matches = (summary_df['match_rate_pct'] == 100).sum()
        total_counties = len(summary_df)

        print(f"\n{'='*80}")
        print(f"VALIDATION COMPLETE")
        print(f"{'='*80}")
        print(f"Perfect matches: {perfect_matches}/{total_counties} counties ({perfect_matches/total_counties*100:.1f}%)")
        print(f"Overall match rate: {summary_df['matches'].sum() / summary_df['rf_test_size'].sum() * 100:.2f}%")

        if perfect_matches == total_counties:
            print("\n✓ All test sets match perfectly!")
        else:
            print(f"\n⚠ {total_counties - perfect_matches} counties have mismatches")
            print("See validation_summary.csv and validate_test_sets.log for details")
    else:
        print("Validation failed - no results generated")
