"""
Evelyn's preprocessing pipeline with PROPERTY-ONLY features.

This module applies Evelyn's preprocessing techniques (log transformation,
winsorization, normalization) but uses ONLY property characteristics:
- char_* features (bedrooms, bathrooms, square footage, etc.)
- Temporal features (sale_year, sale_month, etc.)
- meta_sfh (single-family home indicator)
- fips (county-level geography)

EXCLUDES:
- CALCULATED_TOTAL_VALUE (assessed value)
- All census demographics (census_*_bg, census_*_tract)

This tests: "Do property characteristics alone benefit from preprocessing?"
"""

import pandas as pd
import numpy as np
import logging
import sys
import os

# Add evelyn_files to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'evelyn_files'))
from preprocess import Preprocess

logger = logging.getLogger(__name__)


def get_propertyonly_column_types(df, label_col='SALE_AMOUNT'):
    """
    Get column types for PROPERTY-ONLY feature set.

    Includes:
    - All char_* features (property characteristics)
    - meta_sfh (single-family home indicator)
    - fips (county-level geography)
    - Time variables (generated by Preprocess class)

    Excludes:
    - CALCULATED_TOTAL_VALUE (assessed value)
    - All census_* columns (demographics)
    - latitude/longitude (to avoid leakage)

    Returns:
        continuous_cols, binary_cols, categorical_cols, meta_cols
    """

    # ====================================================================
    # CONTINUOUS FEATURES: Property characteristics only
    # ====================================================================
    continuous_cols = []

    # Add all char_* columns that are numeric (not categorical, not binary)
    for col in df.columns:
        if col.startswith('char_'):
            # Skip categorical and missing indicator columns
            if not col.endswith('_cat') and not col.endswith('_miss'):
                continuous_cols.append(col)

    # Add meta_sfh if it exists and is numeric
    if 'meta_sfh' in df.columns:
        continuous_cols.append('meta_sfh')

    # Add fips for geographic context
    if 'fips' in df.columns:
        continuous_cols.append('fips')

    logger.info(f"Property-only continuous features: {len(continuous_cols)}")

    # ====================================================================
    # BINARY FEATURES: Missing indicators
    # ====================================================================
    binary_cols = [col for col in df.columns
                   if col.startswith('char_') and col.endswith('_miss')]

    logger.info(f"Property-only binary features (missing indicators): {len(binary_cols)}")

    # ====================================================================
    # CATEGORICAL FEATURES: Property categories
    # ====================================================================
    categorical_cols = [col for col in df.columns
                       if col.startswith('char_') and col.endswith('_cat') and col != label_col]

    logger.info(f"Property-only categorical features: {len(categorical_cols)}")

    # ====================================================================
    # META COLUMNS: Everything else (excluded from modeling)
    # ====================================================================
    meta_cols = [
        # Identifiers
        'CLIP', 'PREVIOUS_CLIP', 'OWNER_TRANSFER_COMPOSITE_TRANSACTION_ID',
        'CENSUS_ID', 'tract_id', 'block_group_id', 'tract', 'block_group',

        # Administrative
        'ASSESSED_YEAR', 'SALE_YEAR', 'TAX_YEAR', 'sale_date',
        'TAX_RATE_AREA_CODE', 'CALCULATED_TOTAL_VALUE_SOURCE_CODE',
        'MULTI_OR_SPLIT_PARCEL_CODE',

        # EXPLICITLY EXCLUDE: Assessed values (target leakage)
        'CALCULATED_TOTAL_VALUE',
        'ASSESSED_TOTAL_VALUE',
        'APPRAISED_TOTAL_VALUE',
        'MARKET_TOTAL_VALUE',

        # EXPLICITLY EXCLUDE: All census demographics
        'census_pct_children_bg', 'census_pct_senior_bg', 'census_med_age_bg',
        'census_pct_married_hh_bg', 'census_pct_single_hh_bg',
        'census_pct_high_school_bg', 'census_pct_college_bg', 'census_pct_graduate_bg',
        'census_pct_poverty_bg', 'census_med_hh_inc_bg', 'census_med_per_cap_inc_bg',
        'census_pct_snap_bg', 'census_unemp_rate_bg',
        'census_med_yr_built_bg', 'census_pct_renter_occ_bg', 'census_med_rent_bg',
        'census_pct_children_tract', 'census_pct_senior_tract', 'census_med_age_tract',
        'census_pct_married_hh_tract', 'census_pct_single_hh_tract',
        'census_pct_high_school_tract', 'census_pct_college_tract', 'census_pct_graduate_tract',
        'census_pct_poverty_tract', 'census_med_hh_inc_tract', 'census_med_per_cap_inc_tract',
        'census_pct_snap_tract', 'census_unemp_rate_tract',
        'census_med_yr_built_tract', 'census_pct_renter_occ_tract', 'census_med_rent_tract',

        # Tax amounts (potential leakage)
        'TOTAL_TAX_AMOUNT', 'NET_TAX_AMOUNT',

        # Location (to avoid leakage)
        'latitude', 'longitude', 'address'
    ]

    # Only keep meta columns that exist in data
    meta_cols = [col for col in meta_cols if col in df.columns and col != label_col]

    logger.info(f"Feature set: {len(continuous_cols)} continuous + {len(binary_cols)} binary + {len(categorical_cols)} categorical")
    logger.info(f"Includes: Property characteristics (char_*) + meta_sfh + fips + time vars (generated)")
    logger.info(f"Excludes: Assessed value + census demographics")

    return continuous_cols, binary_cols, categorical_cols, meta_cols


def load_and_prepare_data_propertyonly_evelyn(data_path, cbg_column='block_group_id',
                                               skip_mice=True, wins_pctile=1, log_label=True):
    """
    Load and preprocess Cook County data with PROPERTY-ONLY features + Evelyn's preprocessing.

    Features:
    - Property characteristics: char_* features (~110 features)
    - meta_sfh (single-family home indicator)
    - fips (county geography)
    - Time variables (generated from sale_date)

    Preprocessing (Evelyn's techniques):
    - Log transformation of target
    - Winsorization of outliers (1st/99th percentile)
    - Normalization (StandardScaler)
    - One-hot encoding of categoricals
    - Temporal train-test split

    Args:
        data_path: Path to cook_county.csv
        cbg_column: Name of CBG column (kept in meta but not used in modeling)
        skip_mice: If True, skip MICE imputation (faster, default: True)
        wins_pctile: Percentile for winsorization (default: 1)
        log_label: Whether to apply log transformation to target (default: True)

    Returns:
        X_train_pool, y_train_pool, X_test, y_test, cbg_column_name

    Note:
        - y_train_pool and y_test are LOG-TRANSFORMED if log_label=True
        - Use calculate_metrics with log_transformed=True to auto-inverse-transform
        - cbg_column will NOT be in X_train/X_test (treated as meta)
    """
    logger.info(f"Loading data from {data_path} with Evelyn's preprocessing (PROPERTY-ONLY)")

    # Load raw data
    df = pd.read_csv(data_path, low_memory=False)
    logger.info(f"Loaded data shape: {df.shape}")

    # Get property-only column types
    continuous_cols, binary_cols, categorical_cols, meta_cols = get_propertyonly_column_types(
        df, label_col='SALE_AMOUNT'
    )

    # Initialize Evelyn's Preprocess class
    preprocessor = Preprocess(
        data=df,
        label='SALE_AMOUNT',
        continuous_cols=continuous_cols,
        binary_cols=binary_cols,
        categorical_cols=categorical_cols,
        meta_cols=meta_cols,
        sale_date_col='sale_date',
        geography=None,  # Don't use geography column
        share_non_null=0.5,  # Match Evelyn's config (requires 50% non-null to keep column)
        random_state=42,
        wins_pctile=wins_pctile,
        log_label=log_label,
        mice_iters=3,
        test_size=0.2,
        log_dir='logs'
    )

    # ====================================================================
    # RUN PREPROCESSING PIPELINE
    # ====================================================================
    logger.info("Running Evelyn's preprocessing pipeline (property-only features)...")

    # Step 1: Clean data
    preprocessor.drop_null_labels()
    preprocessor.gen_time_vars()
    preprocessor.drop_single_value_cols()
    preprocessor.drop_mostly_null_cols()
    preprocessor.drop_lowest_ratios()
    preprocessor.drop_repeat_sales()

    # Step 2: Encode categoricals
    preprocessor.one_hot()
    preprocessor.renumber_geo_col()

    # Step 3: Train-test split (temporal)
    preprocessor.train_test_split()

    # ====================================================================
    # FIX STRING COLUMNS BEFORE WINSORIZATION
    # Some continuous columns may have been incorrectly classified or contain strings
    # ====================================================================
    for col in preprocessor._continuous_cols:
        if col in preprocessor.X_train.columns:
            if preprocessor.X_train[col].dtype == 'object':
                logger.warning(f"Column {col} is object type in continuous_cols, attempting to convert")
                try:
                    preprocessor.X_train[col] = pd.to_numeric(preprocessor.X_train[col], errors='coerce')
                    preprocessor.X_test[col] = pd.to_numeric(preprocessor.X_test[col], errors='coerce')
                except:
                    logger.warning(f"Failed to convert {col}, removing from continuous_cols")
                    preprocessor._continuous_cols.remove(col)

    # Step 4: Winsorize outliers
    if wins_pctile > 0:
        logger.info(f"Winsorizing at {wins_pctile}th percentile...")
        preprocessor.winsorize_continuous()
        preprocessor.winsorize_label()

    # Step 5: Log transform target
    if log_label:
        logger.info("Applying log transformation to target...")
        preprocessor.log_label()

    # Step 6: Drop problematic columns
    preprocessor._drop_problematic_cols_from_splits()

    # Step 7: Impute missing values
    if skip_mice:
        logger.info("Skipping MICE imputation, using median/mode imputation")
        for col in preprocessor.X_train.columns:
            if preprocessor.X_train[col].isnull().any():
                if pd.api.types.is_numeric_dtype(preprocessor.X_train[col]):
                    fill_value = preprocessor.X_train[col].median()
                    preprocessor.X_train[col] = preprocessor.X_train[col].fillna(fill_value)
                    preprocessor.X_test[col] = preprocessor.X_test[col].fillna(fill_value)
                else:
                    fill_value = preprocessor.X_train[col].mode()[0] if len(preprocessor.X_train[col].mode()) > 0 else 0
                    preprocessor.X_train[col] = preprocessor.X_train[col].fillna(fill_value)
                    preprocessor.X_test[col] = preprocessor.X_test[col].fillna(fill_value)
    else:
        logger.info("Running MICE imputation (this may take a while)...")
        preprocessor.impute_missings_with_mice()

    # Step 8: Normalize continuous features
    logger.info("Normalizing continuous features with StandardScaler...")
    preprocessor.normalize_continuous_cols()

    # Extract processed data
    X_train = preprocessor.X_train
    y_train = preprocessor.y_train
    X_test = preprocessor.X_test
    y_test = preprocessor.y_test

    # ====================================================================
    # FIX INDEX MISMATCH: Reset index so sample_train_set can work
    # Evelyn's preprocessing drops rows, so indices are no longer sequential
    # ====================================================================
    X_train = X_train.reset_index(drop=True)
    y_train = y_train.reset_index(drop=True)
    X_test = X_test.reset_index(drop=True)
    y_test = y_test.reset_index(drop=True)

    # ====================================================================
    # FIX STRING COLUMNS: Convert all remaining columns to numeric
    # Some columns may be strings after preprocessing
    # ====================================================================
    for col in X_train.columns:
        if X_train[col].dtype == 'object':
            try:
                X_train[col] = pd.to_numeric(X_train[col], errors='coerce')
                X_test[col] = pd.to_numeric(X_test[col], errors='coerce')
                logger.warning(f"Converted column {col} from object to numeric")
            except:
                logger.warning(f"Could not convert column {col} to numeric, dropping it")
                X_train = X_train.drop(columns=[col])
                X_test = X_test.drop(columns=[col])

    # ====================================================================
    # FINAL SUMMARY
    # ====================================================================
    logger.info(f"Preprocessing complete!")
    logger.info(f"Train pool shape: {X_train.shape}")
    logger.info(f"Test set shape: {X_test.shape}")
    logger.info(f"Target log-transformed: {log_label}")
    logger.info(f"Features: Property characteristics only (no assessed value, no census)")

    # Log first few features for verification
    logger.info(f"Sample features: {X_train.columns.tolist()[:10]}...")

    # Return in same format as original load_and_prepare_data
    # Note: X_train is the full training set (can be subsampled later)
    # Note: y_train and y_test are log-transformed if log_label=True
    # Note: cbg_column is NOT in X_train/X_test (it's in meta_cols)
    return X_train, y_train, X_test, y_test, cbg_column
